source "http://rubygems.org/"
gem "bundler"
gem "garb"
gem "jekyll"
gem "mocha"
gem "passenger"
gem "rails", "2.3.5"
gem "rack", "1.0.1"
gem "rubygems-update"
gem "shoulda"
gem "sqlite3-ruby", "1.2.5"
gem "timecop"
gem "yard"
gem "ruby-debug"
gem "redis", "2.0.1"
